### ISSUE TITLE
kanban board setup

### ISSUE THREAD

**Issue by mercymugambi** [mercymugambi/space-travel-project#24]
I @mercymugambi and @anbehindY have been paired to work on this space travel application.
Below is the link to the kanban board with tasks assigned to each one of us.

[space-travel-project](https://github.com/mercymugambi/space-travel-project/projects/1)

**Comment by AlphaNtihinduka** [comment]
## Hi @mercymugambi & @anbehindY 🙋‍♂️
Good job working on your Kanban board.👏  
You still need to implement a few on the project but you are almost there!!! 🚶 : 

TO HIGHLIGHT:
Assigning the group assignments to both students. ✔️

# STATUS: Required Changes :recycle: 

![close](https://user-images.githubusercontent.com/99394374/210771148-619a4265-33b2-4e68-8901-6bb52693d6de.gif)

 # Required Changes :recycle: 
- [ ] Please ensure that the required category cards are evenly assigned. At this stage, I have noticed that you are missing the `conditional components` category for @mercymugambi 😞. Kindly assign her to balance the tasks ☺️.

## Optional suggestions
N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or slack channel if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK :crossed_fingers: :four_leaf_clover:

**Comment by roshan-bajgain** [comment]
Hi @mercymugambi and @anbehindY, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Equally assign the work ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
